pub_rate: 0.5 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  power:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Power System'
    timeout: 5.0
    startswith: ['Battery', 'Laptop Battery']
  network:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Network'
    timeout: 5.0
    startswith: ['eth', 'wlan']
  cpu:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'System'
    timeout: 5.0
    startswith: ['cpu', 'Memory']
  robot:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Robot'
    timeout: 5.0
    startswith: ['Main Battery']
    
